
Profiles:

    AutoOrdererGenesis:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
        Consortiums:
            Auto:
                Organizations:
                    - *Manufacturer
                    - *Supplier1
                    - *Supplier1A
                    - *Supplier1B
                    - *Supplier2
                    - *Supplier2A
                    - *Agency

    Channel1:
        Consortium: Auto
        Application:
            <<: *ApplicationDefaults
            Organizations:
                  - *Manufacturer
                  - *Supplier1
                  - *Supplier1A
                  - *Agency

    Channel2:
        Consortium: Auto
        Application:
            <<: *ApplicationDefaults
            Organizations:
              - *Manufacturer
              - *Supplier1
              - *Supplier1B
              - *Agency

    Channel3:
        Consortium: Auto
        Application:
            <<: *ApplicationDefaults
            Organizations:
              - *Manufacturer
              - *Supplier2
              - *Supplier2A
              - *Agency
             
Organizations:

    - &OrdererOrg
        Name: OrdererMSP
        ID: OrdererMSP

        MSPDir: crypto-config/ordererOrganizations/example.com/msp

    - &Supplier1
        Name: Supplier1MSP
        ID: Supplier1MSP

        MSPDir: crypto-config/peerOrganizations/Supplier1.com/msp

        AnchorPeers:
            - Host: peer0.Supplier1.com
              Port: 7051

    - &Supplier1A
        Name: Supplier1AMSP
        ID: Supplier1AMSP

        MSPDir: crypto-config/peerOrganizations/Supplier1A.com/msp

        AnchorPeers:
            - Host: peer0.Supplier1A.com
              Port: 7051

    - &Supplier1B
        Name: Supplier1BMSP
        ID: Supplier1BMSP

        MSPDir: crypto-config/peerOrganizations/Supplier1B.com/msp

        AnchorPeers:
            - Host: peer0.Supplier1B.com
              Port: 7051

    - &Supplier2
        Name: Supplier2MSP
        ID: Supplier2MSP

        MSPDir: crypto-config/peerOrganizations/Supplier2.com/msp

        AnchorPeers:
            - Host: peer0.Supplier2.com
              Port: 7051

    - &Supplier2A
        Name: Supplier2AMSP
        ID: Supplier2AMSP

        MSPDir: crypto-config/peerOrganizations/Supplier2A.com/msp

        AnchorPeers:
            - Host: peer0.Supplier2A.com
              Port: 7051

    - &Agency
        Name: AgencyMSP
        ID: AgencyMSP

        MSPDir: crypto-config/peerOrganizations/Agency.com/msp

        AnchorPeers:
            - Host: peer0.Agency.com
              Port: 7051
    - &Manufacturer
        Name: ManufacturerMSP
        ID: ManufacturerMSP

        MSPDir: crypto-config/peerOrganizations/Manufacturer.com/msp

        AnchorPeers:
            - Host: peer0.Manufacturer.com
              Port: 7051

Orderer: &OrdererDefaults
    OrdererType: solo

    Addresses:
        - orderer.example.com:7050

    BatchTimeout: 2s

    BatchSize:

        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB

    Organizations:


Application: &ApplicationDefaults
    Organizations:
