version: '2'

networks:
  auto:

services:
  orderer.example.com:
    image: hyperledger/fabric-orderer
    container_name: orderer.example.com
    environment:
      - GODEBUG=netdns=go
      - ORDERER_GENERAL_LOGLEVEL=info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
    volumes:
      - ./artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
    command: orderer
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    ports:
      - 7050:7050
    networks:
      - auto

  peer0.Manufacturer.com:
    container_name: peer0.Manufacturer.com
    extends:
      file: ./peer.yaml
      service: peer
    environment:
      - CORE_PEER_ID=peer0.Manufacturer.com
      - CORE_PEER_ADDRESS=peer0.Manufacturer.com:7051
      - CORE_PEER_LOCALMSPID=ManufacturerMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.Manufacturer.com:7051
    volumes:
      - ./crypto-config/peerOrganizations/Manufacturer.com/peers/peer0.Manufacturer.com/msp:/etc/hyperledger/msp/peer
    ports:
      - 7051:7051
      - 7053:7053
    depends_on:
      - orderer.example.com
    networks:
      - auto

  peer0.Supplier1.com:
    container_name: peer0.Supplier1.com
    extends:
      file: ./peer.yaml
      service: peer
    environment:
      - CORE_PEER_ID=peer0.Supplier1.com
      - CORE_PEER_ADDRESS=peer0.Supplier1.com:7051
      - CORE_PEER_LOCALMSPID=Supplier1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.Supplier1.com:7051
    volumes:
      - ./crypto-config/peerOrganizations/Supplier1.com/peers/peer0.Supplier1.com/msp:/etc/hyperledger/msp/peer
    ports:
      - 10051:7051
      - 10053:7053
    depends_on:
      - orderer.example.com
    networks:
      - auto

  peer0.Supplier1A.com:
    container_name: peer0.Supplier1A.com
    extends:
      file: ./peer.yaml
      service: peer
    environment:
      - CORE_PEER_ID=peer0.Supplier1A.com
      - CORE_PEER_ADDRESS=peer0.Supplier1A.com:7051
      - CORE_PEER_LOCALMSPID=Supplier1AMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.Supplier1A.com:7051
    volumes:
      - ./crypto-config/peerOrganizations/Supplier1A.com/peers/peer0.Supplier1A.com/msp:/etc/hyperledger/msp/peer
    ports:
      - 9051:7051
      - 9053:7053
    depends_on:
      - orderer.example.com
    networks:
      - auto

  peer0.Supplier1B.com:
        container_name: peer0.Supplier1B.com
        extends:
          file: ./peer.yaml
          service: peer
        environment:
          - CORE_PEER_ID=peer0.Supplier1B.com
          - CORE_PEER_ADDRESS=peer0.Supplier1B.com:7051
          - CORE_PEER_LOCALMSPID=Supplier1BMSP
          - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
          - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.Supplier1B.com:7051
        volumes:
          - ./crypto-config/peerOrganizations/Supplier1B.com/peers/peer0.Supplier1B.com/msp:/etc/hyperledger/msp/peer
        ports:
          - 8051:7051
          - 8053:7053
        depends_on:
          - orderer.example.com
        networks:
          - auto

  peer0.Supplier2.com:
        container_name: peer0.Supplier2.com
        extends:
          file: ./peer.yaml
          service: peer
        environment:
          - CORE_PEER_ID=peer0.Supplier2.com
          - CORE_PEER_ADDRESS=peer0.Supplier2.com:7051
          - CORE_PEER_LOCALMSPID=Supplier2MSP
          - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
          - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.Supplier2.com:7051
        volumes:
          - ./crypto-config/peerOrganizations/Supplier2.com/peers/peer0.Supplier2.com/msp:/etc/hyperledger/msp/peer
        ports:
          - 11051:7051
          - 11053:7053
        depends_on:
          - orderer.example.com
        networks:
          - auto

  peer0.Supplier2A.com:
        container_name: peer0.Supplier2A.com
        extends:
          file: ./peer.yaml
          service: peer
        environment:
          - CORE_PEER_ID=peer0.Supplier2A.com
          - CORE_PEER_ADDRESS=peer0.Supplier2A.com:7051
          - CORE_PEER_LOCALMSPID=Supplier2AMSP
          - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
          - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.Supplier2A.com:7051
        volumes:
          - ./crypto-config/peerOrganizations/Supplier2A.com/peers/peer0.Supplier2A.com/msp:/etc/hyperledger/msp/peer
        ports:
          - 12051:7051
          - 12053:7053
        depends_on:
          - orderer.example.com
        networks:
          - auto

  peer0.Agency.com:
        container_name: peer0.Agency.com
        extends:
          file: ./peer.yaml
          service: peer
        environment:
          - CORE_PEER_ID=peer0.Agency.com
          - CORE_PEER_ADDRESS=peer0.Agency.com:7051
          - CORE_PEER_LOCALMSPID=AgencyMSP
          - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
          - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.Agency.com:7051
        volumes:
          - ./crypto-config/peerOrganizations/Agency.com/peers/peer0.Agency.com/msp:/etc/hyperledger/msp/peer
        ports:
          - 13051:7051
          - 13053:7053
        depends_on:
          - orderer.example.com
        networks:
          - auto

  cli.Manufacturer:
    extends:
      file: ./cli.yaml
      service: cli
    container_name: cli.Manufacturer
    environment:
      - CORE_PEER_ID=cli.Manufacturer.com
      - CORE_PEER_ADDRESS=peer0.Manufacturer.com:7051
      - CORE_PEER_LOCALMSPID=ManufacturerMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@Manufacturer.com/msp
    volumes:
      - ./crypto-config/peerOrganizations/Manufacturer.com:/etc/hyperledger/msp
    depends_on:
      - orderer.example.com
      - peer0.Manufacturer.com
    networks:
      - auto

  cli.Supplier1:
    extends:
      file: ./cli.yaml
      service: cli
    container_name: cli.Supplier1
    environment:
      - CORE_PEER_ID=cli.Supplier1.com
      - CORE_PEER_ADDRESS=peer0.Supplier1.com:7051
      - CORE_PEER_LOCALMSPID=Supplier1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@Supplier1.com/msp
    volumes:
      - ./crypto-config/peerOrganizations/Supplier1.com:/etc/hyperledger/msp
    depends_on:
      - orderer.example.com
      - peer0.Supplier1.com
    networks:
      - auto

  cli.Supplier1A:
    extends:
      file: ./cli.yaml
      service: cli
    container_name: cli.Supplier1A
    environment:
      - CORE_PEER_ID=cli.Supplier1A.com
      - CORE_PEER_ADDRESS=peer0.Supplier1A.com:7051
      - CORE_PEER_LOCALMSPID=Supplier1AMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@Supplier1A.com/msp
    volumes:
      - ./crypto-config/peerOrganizations/Supplier1A.com:/etc/hyperledger/msp
    depends_on:
      - orderer.example.com
      - peer0.Supplier1A.com
    networks:
      - auto

  cli.Supplier1B:
    extends:
      file: ./cli.yaml
      service: cli
    container_name: cli.Supplier1B
    environment:
      - CORE_PEER_ID=cli.Supplier1B.com
      - CORE_PEER_ADDRESS=peer0.Supplier1B.com:7051
      - CORE_PEER_LOCALMSPID=Supplier1BMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@Supplier1B.com/msp
    volumes:
      - ./crypto-config/peerOrganizations/Supplier1B.com:/etc/hyperledger/msp
    depends_on:
      - orderer.example.com
      - peer0.Supplier1B.com
    networks:
      - auto

  cli.Supplier2:
    extends:
      file: ./cli.yaml
      service: cli
    container_name: cli.Supplier2
    environment:
      - CORE_PEER_ID=cli.Supplier2.com
      - CORE_PEER_ADDRESS=peer0.Supplier2.com:7051
      - CORE_PEER_LOCALMSPID=Supplier2MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@Supplier2.com/msp
    volumes:
      - ./crypto-config/peerOrganizations/Supplier2.com:/etc/hyperledger/msp
    depends_on:
      - orderer.example.com
      - peer0.Supplier2.com
    networks:
      - auto

  cli.Supplier2A:
    extends:
      file: ./cli.yaml
      service: cli
    container_name: cli.Supplier2A
    environment:
      - CORE_PEER_ID=cli.Supplier2A.com
      - CORE_PEER_ADDRESS=peer0.Supplier2A.com:7051
      - CORE_PEER_LOCALMSPID=Supplier2AMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@Supplier2A.com/msp
    volumes:
      - ./crypto-config/peerOrganizations/Supplier2A.com:/etc/hyperledger/msp
    depends_on:
      - orderer.example.com
      - peer0.Supplier2A.com
    networks:
      - auto

  cli.Agency:
    extends:
      file: ./cli.yaml
      service: cli
    container_name: cli.Agency
    environment:
      - CORE_PEER_ID=cli.Agency.com
      - CORE_PEER_ADDRESS=peer0.Agency.com:7051
      - CORE_PEER_LOCALMSPID=AgencyMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@Agency.com/msp
    volumes:
      - ./crypto-config/peerOrganizations/Agency.com:/etc/hyperledger/msp
    depends_on:
      - orderer.example.com
      - peer0.Agency.com
    networks:
      - auto
